### ISSUE TITLE
Lost commits due to a force push!

### ISSUE THREAD

**Issue by sdball** [activemerchant/active_merchant#2029] opened 2016-02-24 18:01 UTC
Whoop! It looks like a force push today has lost some commits on master:

```
(activemerchant) $ git fetch
From git://github.com/activemerchant/active_merchant
 + ca6aa89...b021c2f master     -> origin/master  (forced update)
 + 24b8d23...b9b8524 bugfix/mercury-max-track1 -> origin/bugfix/mercury-max-track1  (forced update)
```

Checking divergence of my local repo vs origin:

```
changes from local master to remote origin/master:

incoming:

* b021c2f - (origin/master, origin/HEAD) Remove App55 (21 minutes ago) <ThereExistsX>
 b/README.md                                   |    1
 b/test/fixtures.yml                           |    4
 lib/active_merchant/billing/gateways/app55.rb |  176 --------------------------
 test/remote/gateways/remote_app55_test.rb     |   65 ---------
 test/unit/gateways/app55_test.rb              |   51 -------
 5 files changed, 297 deletions(-)


outgoing:

* ca6aa89 - (HEAD -> master) SagePay: Update VISA Electron ranges (2 days ago) <Stephen Ball>
 CHANGELOG                                          |    1
 lib/active_merchant/billing/credit_card.rb         |    5 ++
 lib/active_merchant/billing/credit_card_methods.rb |   31 +++++++++++++
 lib/active_merchant/billing/gateways/sage_pay.rb   |    5 --
 test/unit/credit_card_methods_test.rb              |   24 ++++++++++
 test/unit/gateways/sage_pay_test.rb                |   47 +++------------------
 6 files changed, 70 insertions(+), 43 deletions(-)

* c3d030b - Cashnet: Default custcode option and proper redirect handling (2 days ago) <Thomas Hoen>
 CHANGELOG                                       |    1 +
 lib/active_merchant/billing/gateways/cashnet.rb |    7 +++++--
 test/unit/gateways/cashnet_test.rb              |   13 +++++++++++++
 3 files changed, 19 insertions(+), 2 deletions(-)

* c8cdfc8 - Clearhaus: Make request signing more transparent & robust (8 days ago) <Stephen Ball>
 CHANGELOG                                         |    1
 lib/active_merchant/billing/gateways/clearhaus.rb |    7 ++++
 test/remote/gateways/remote_clearhaus_test.rb     |   24 +++++++++++++++-
 test/unit/gateways/clearhaus_test.rb              |   32 ++++++++++++++++++++++
 4 files changed, 62 insertions(+), 2 deletions(-)

* 0ecbd0b - NCRSecurePay: Fix production URL (9 days ago) <Ryan Daigle>
 CHANGELOG                                              |    1 +
 lib/active_merchant/billing/gateways/ncr_secure_pay.rb |    2 +-
 2 files changed, 2 insertions(+), 1 deletion(-)

* 9231e0d - Give sdball credit for Stripe ACH (13 days ago) <Ryan Daigle>
 CHANGELOG |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

* f2a7ea3 - Add ACH support to Stripe (2 weeks ago) <Stephen Ball>
 CHANGELOG                                      |    1
 lib/active_merchant/billing/gateways/stripe.rb |   65 ++++++++++++++++--
 test/fixtures.yml                              |    5 +
 test/remote/gateways/remote_stripe_test.rb     |   71 +++++++++++++++++++
 test/unit/gateways/stripe_test.rb              |   90 +++++++++++++++++++++++++
 5 files changed, 225 insertions(+), 7 deletions(-)
```

In other words, we've lost the following commits as they were orphaned by the force push:

```
$ git outgoing origin/master
ca6aa899fea89257a0cbdfaef93ef01e064c80c3
c3d030b971ded203c9df6373a263b38488d8aa22
c8cdfc8be1c325ec165e9e482c51cb891a41ab83
0ecbd0bbc16ccf86eafa60c5627e9dfa15c7aaeb
9231e0d5af01f78ee89db9e5ea69df4c2a05bb78
f2a7ea3ed298038529acce7552b733ade8f3bc90
```

We may have lost more commits as I'm not 100% certain my local repo was up to date before the force push.

It's possible to rebuild the history from any clone of the repo that had the commit history from before the force push. I'm happy to help sort out the commits but we'll need to get someone with push rights to actually do the fixing.

**Comment by duff** [comment] 2016-02-24 18:05
@activemerchant/developers I'd love to know if anyone has more recent local commits.

**Comment by ryanbalsdon** [comment] 2016-02-24 18:14
I did a merge about 3 hours ago:
```
$ git push origin master
Counting objects: 12, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 1.41 KiB | 0 bytes/s, done.
Total 12 (delta 11), reused 0 (delta 0)
To git@github.com:activemerchant/active_merchant.git
   ca6aa89..033f2fc  master -> master
```

This wasn't caused by that, was it?

**Comment by ThereExistsX** [comment] 2016-02-24 18:16
No, it was definitely me. I'll ping you @ryanbalsdon you probably have a better copy of AM than I do.

**Comment by rwdaigle** [comment] 2016-02-24 18:18
I can reset master to the state I have, which was last updated on Feb, 18th w/ sha `ca6aa89` and includes all the missing commits listed above.

This will have the effect of orphaning the following commits:

* https://github.com/activemerchant/active_merchant/commit/b021c2fc27da69f081c08ecf9e171e54db340ab8
* https://github.com/activemerchant/active_merchant/commit/8b10b2b046b8cc9d7cb20b0568a6b53ea090e884

@ThereExistsX can you confirm you have both of these commits locally? If so, I will reset master here and you can re-apply your commits after rebasing?

```bash
$ git fetch

# On your feature branch
$ git rebase origin/master

# Then, in master
$ git merge --ff-only feature-branch
```

**Comment by ThereExistsX** [comment] 2016-02-24 18:20
@rwdaigle I do have both of those locally, and I'll reapply them after you reset. Sorry for the trouble.

**Comment by girasquid** [comment] 2016-02-24 18:21
After this is sorted out, should we turn on branch protection to block force pushes to master?

**Comment by duff** [comment] 2016-02-24 18:22
@girasquid Yes. :)

**Comment by girasquid** [comment] 2016-02-24 18:22
Ok! Will do, once we're feeling confident.

**Comment by duff** [comment] 2016-02-24 18:22
Based on @ryanbalsdon's comments, I suspect he has a more recent set of commits.

**Comment by sdball** [comment] 2016-02-24 18:23
Sounds like the best course would be resetting to @ryanbalsdon's commit (https://github.com/activemerchant/active_merchant/commit/033f2fc) and force pushing that to master. Then turning on force push protection. :smile:

**Comment by rwdaigle** [comment] 2016-02-24 18:23
@ThereExistsX no worries! It's really hard to lose stuff w/ git :)

@ryanbalsdon let me know what your most recent local commits are to see if you should do the reset?

@girasquid 

>  should we turn on branch protection to block force pushes to master?

Makes a lot of sense to me! Just a good practice all around anyway.

**Comment by aprofeit** [comment] 2016-02-24 18:23
> Sounds like the best course would be resetting to @ryanbalsdon's commit (033f2fc) and force pushing that to master. Then turning on force push protection. :smile:

:+1:

**Comment by ryanbalsdon** [comment] 2016-02-24 18:26
This is my local copy of master:
```
033f2fc83178c35ec7a580f42cd44cd60e69df8f
ca6aa899fea89257a0cbdfaef93ef01e064c80c3
c3d030b971ded203c9df6373a263b38488d8aa22
c8cdfc8be1c325ec165e9e482c51cb891a41ab83
0ecbd0bbc16ccf86eafa60c5627e9dfa15c7aaeb
9231e0d5af01f78ee89db9e5ea69df4c2a05bb78
f2a7ea3ed298038529acce7552b733ade8f3bc90
8b10b2b046b8cc9d7cb20b0568a6b53ea090e884
```
so it's just that one patch (033f2fc) that's missing

**Comment by rwdaigle** [comment] 2016-02-24 18:32
@ryanbalsdon :+1: you good force pushing to master w/ head at `033f2fc?

**Comment by ryanbalsdon** [comment] 2016-02-24 18:37
ok, force pushing now

**Comment by sdball** [comment] 2016-02-24 18:38
Looks good here!

```
$ git fetch
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From git://github.com/activemerchant/active_merchant
 + b021c2f...033f2fc master     -> origin/master  (forced update)
```

```
$ git div

changes from local master to remote origin/master:

incoming:

* 033f2fc - (origin/master, origin/HEAD) Mercury: Stripping the start and end sentinels on card-present track data for max-length track1 requests Closes
 CHANGELOG                                       |    1 +
 lib/active_merchant/billing/gateways/mercury.rb |   16 ++++++++++++----
 test/unit/gateways/mercury_test.rb              |   14 ++++++++++++++
 3 files changed, 27 insertions(+), 4 deletions(-)


outgoing:
```

**Comment by ThereExistsX** [comment] 2016-02-24 18:40
Thank you so much, I am again, really sorry. I'll get those two orphaned commits rebased in and pushed up in a few minutes.

**Comment by rwdaigle** [comment] 2016-02-24 18:40
Great, thanks @ryanbalsdon! Closing this 

@ThereExistsX just a reminder that you'll still need to get `b021c2f` and `8b10b2b` merged in and pushed.

**Comment by girasquid** [comment] 2016-02-24 18:41
branch protection from force pushes for `master` has been turned on.

**Closed by rwdaigle** 2016-02-24 18:40 UTC

**Comment by duff** [comment] 2016-02-24 18:42
@ThereExistsX no worries!

@girasquid Thanks!

**Comment by rwdaigle** [comment] 2016-02-24 18:42
@ThereExistsX no sweat! We've all been there *at least* once in our git lives :)

**Comment by sdball** [comment] 2016-02-24 18:43
Once again, thanks Git for being awesome!

@ThereExistsX: We've all been there :+1:

**Comment by ntalbott** [comment] 2016-02-24 18:53
So right after I got a commit bit to this project back in 2011, I totally hosed `master` trying to merge this: https://github.com/activemerchant/active_merchant/commit/6db49caee6958771de6bbef80dc041a4a1c2b591. @soleone was awesome about it and helped me clean up my mess. We've all been there!

**Comment by ThereExistsX** [comment] 2016-02-24 19:07
Thank you so much, guys. I'm still feeling like I'm going to be sick, but at least a little less so.
